
* 

** $\{bm}$ が最小二乗問題 $\min{\bm{x}\in \mathbb{R}^n} \|\bm{b}-A\bm{x}\|_2$ の解であるとき、かつそのときに限り正規方程式 $A^TA\bm{x}=A^T\bm{b}$ の解であることを示せ。
   
** 行列 $A \in \mathbb{R}^{m\times n}, rank\ A=n$ の特異値分解は
   \begin{eqnarray*}
   A = U \Sigma V^T,\ U\in\mathbb{R}^{m\times n},\ \Sigma\in\mathbb{R}^{n\times n},\ V\in\mathbb{R}^{n\times n},\\
   U^TU=I,\ VV^T=V^TV=I
   \end{eqnarray*}
   　と表せる。このとき、最小二乗問題 $\min_{\bm{x}\in\mathbb{R}^n}\|\bm{b}-A\bm{x}\|$ の解は $\bm{x} = V\Sigma^{-1}U^T\bm{b}$ であることを示せ。
   
** 行列 $A$ , ベクトル $\bm{b}$ を
   
   \begin{eqnarray}
   \left (
\begin{array}{ccc}
1&1&1 \\
1&2&2 \\
1&2&3 \\
1&2&3
\end{array}
\right )\\
\left (
\begin{array}{c}
4 \\
5 \\
6 \\
7
\end{array}
\right )
   \end{eqnarray}
   　とし、最小二乗問題 $\min_{\bm{x}}\|\bm{b}-A\bm{x}\|_{2}$ を特異値分解を用いて解く Scilab プログラムを作成し、解を求めよ。

* 
  　手書き数字の画像データセットである MNIST を用いて手書き数字の画像認識を行う。MNISTの行列データは manaba にアップロードされているため、ダウンロードして用いること。ファイルから得られる行列 X は画像データであり、各列に 1 枚の画像が格納されている。Y は各画像が属するグループを示している。 test＿X, test＿Y はそれぞれテストデータと各画像が属するグループを示している。今回の課題では訓練データとテストデータを 10,000 個ずつ用いる。
  　 manaba にアップロードされている showMNISTimg.sci を使用すると行列 X の先頭から i 番目の列に格納されている訓練データを画像として表示することが出来る。

** 行列 $X\in\mathbb{R}^{m\times n}, Y\in \mathbb{R}^{10\times n}$ に対し、最小二乗問題
   \begin{eqnarray*}
   \min_{W\in\mathbb{R}^{10\times m}}\|Y-WX\|_F
   \end{eqnarray*}

   　の特異値分解を用いて解く Scilab プログラムを作成せよ。行列 X の特異値を $\sigma_1\geq\sigma_2\geq\cdots\geq\sigma_m$ としたとき、k を $\sigma_k/\sigma_1\geq 10^{-14}$ を満たすような最大の整数とする。k 個の特異値とそれぞれの特異値に対応する k 本の特異ベクトルを用いて行列 X の低ランク近似を行うこと。ここでは $m = 784, n=10,000$ である。

** 得られた行列 $W$ を用いてテストデータの画像がどのグループに属するか判定することができる。manaba にアップロードされている check.sci を用いて (2-1) で得られた W に対して処理判定を行い、画像認識の正答率を求めよ。check(W, test＿X, test＿Y) と実行すると正答率を求めることができる。

** (2-2) では訓練データを 10,000 個用いて画像認識を行ったが、訓練データ数を帰ることで画像認識の正答率は変化する。訓練データ数を行列の先端の列から $1,000, 2,000, \dots , 10,000$ 個としたときの画像認識の正答率を求める Scilab プログラムを作成し、それぞれの訓練データ数における正答率をグラフに描画せよ。

** 行列 X の低ランク近似を行う際の整数 k を $\sigma_k/\sigma_1\geq\delta$ を満たすような最大の整数とする。このとき、閾値 $\delta$ を $0.005, 0.01, 0.015,\dots , 0.1$ と変えたときの画像認識の正答率を求める Scilab プログラムを作成し、各しきい値に対する正答率をグラフに描画せよ。ただし、訓練データは 10,000個用いること。
